name: "Linux"

strategy:
  matrix:
    gcc8:
      Container: pleroux0/devel-gcc8:latest
    clang7-libstdc++:
      Container: pleroux0/devel-clang7:latest
      CXXFLAGS: -stdlib=libstdc++
    clang7-libc++:
      Container: pleroux0/devel-clang7:latest
      CXXFLAGS: -stdlib=libc++
    clang7-sanitize-undefined:
      Container: pleroux0/devel-clang7:latest
      CXXFLAGS: -fsanitize=undefined
    clang7-sanitize-address:
      Container: pleroux0/devel-clang7:latest
      CXXFLAGS: -fsanitize=address
      LSAN_OPTIONS: "verbosity=1:log_threads=1"

trigger:
  batch: true
  branches:
    include:
    - '*'

pool:
  vmImage: 'Ubuntu-16.04'

container:
  image: $[ variables['Container'] ]
  options: "--cap-add SYS_PTRACE"

steps:
- script: mkdir -p build
  displayName: 'Make build folder'

- script: sudo apt-get -y install libsuitesparse-dev python3-dev
  displayName: 'Install APT dependencies'

- script: conan install ..
  displayName: 'Install Conan dependencies'
  workingDirectory: build

- script: cmake ..
  workingDirectory: build
  displayName: 'Configure'

- script: cmake --build .
  workingDirectory: build
  displayName: 'Build'

- script: ctest --output-on-failure
  workingDirectory: build
  displayName: 'Test'
