name: "Linux"

resources:
  containers:
  - container: gcc8
    image: pleroux0/devel-gcc8:latest
  - container: clang7
    image: pleroux0/devel-clang7:latest
  - container: clang7_ptrace
    image: pleroux0/devel-clang7:latest
    options: --cap-add SYS_PTRACE

strategy:
  matrix:
    gcc8:
      Container: gcc8
    clang7-libstdc++:
      Container: clang7
      CXXFLAGS: -stdlib=libstdc++
    clang7-libc++:
      Container: clang7
      CXXFLAGS: -stdlib=libc++
    clang7-sanitize-undefined:
      Container: clang7
      CXXFLAGS: -fsanitize=undefined
    clang7-sanitize-address:
      Container: clang7_ptrace
      CXXFLAGS: -fsanitize=address

trigger:
  batch: true
  branches:
    include:
    - '*'

pool:
  vmImage: 'Ubuntu-16.04'

container: $[ variables['Container'] ]

steps:
- script: mkdir -p build
  displayName: 'Make build folder'

- script: |
    sudo apt-get -y update
    sudo apt-get -y install libsuitesparse-dev python3-dev
  displayName: 'Install APT dependencies'

- #script: conan install ..
  #displayName: 'Install Conan dependencies'
  #workingDirectory: build

- script: cmake ..
  workingDirectory: build
  displayName: 'Configure'

- script: cmake --build .
  workingDirectory: build
  displayName: 'Build'

- script: ctest --output-on-failure
  workingDirectory: build
  displayName: 'Test'
