#!/usr/bin/env python3
import os
import fnmatch
import sys

def find_difference(path_1, path_2):
    l1 = l2 = True
    with open(path_1, 'r') as f1, open(path_2, 'r') as f2:
        while l1 and l2:
            l1 = f1.readline()
            l2 = f2.readline()
            if l1 != l2:
                return False
    return True

def main():
    scriptpath = os.path.dirname(os.path.realpath(__file__))
    if os.name == 'nt':
        josimpath = '{0}/../build/Release/josim-cli.exe'.format(scriptpath)
        null = '> NULL 2>&1'
    else:
        josimpath = '{0}/../build/josim-cli'.format(scriptpath)
        null = '&> /dev/null'
    path = '{0}/../test/'.format(scriptpath);
    reference_path = '{0}/../test/reference/'.format(scriptpath);
    pattern = 'ex_*.cir'

    ex_files = [f for f in fnmatch.filter(os.listdir(path), pattern)]

    print("Voltage mode tests")
    print("==================")
    for f in ex_files:
        file = os.path.join(path, f)
        pre, ext = os.path.splitext(file)
        csvfile = pre + '.csv'
        if("_wr" in file):
            cmd = '{0} -c 1 -o {1} {2} {3}'.format(josimpath, csvfile, file, null)
        else:
            cmd = '{0} -o {1} {2} {3}'.format(josimpath, csvfile, file, null)
        returned_value = os.system(cmd)
        if(returned_value == 0):
            print('PASS:', f)
        else:
            print('FAIL:', f)
        reference_file = os.path.join(reference_path, f)
        pre, ext = os.path.splitext(reference_file)
        reference_file = pre + '.csv'
        if(find_difference(reference_file, csvfile)):
            print('MATCH:', f)
            os.remove(csvfile)
        else:
            print('MISSMATCH:', f)
    print("Phase mode tests")
    print("================")
    for f in ex_files:
        file = os.path.join(path, f)
        pre, ext = os.path.splitext(file)
        csvfile = pre + '_phase.csv'
        if("_wr" in file):
            cmd = '{0} -a 1 -c 1 -o {1} {2} {3}'.format(josimpath, csvfile, file, null)
        else:
            cmd = '{0} -a 1 -o {1} {2} {3}'.format(josimpath, csvfile, file, null)
        returned_value = os.system(cmd)
        if(returned_value == 0):
            print('PASS:', f)
        else:
            print('FAIL:', f)
        reference_file = os.path.join(reference_path, f)
        pre, ext = os.path.splitext(reference_file)
        reference_file = pre + '_phase.csv'
        if(find_difference(reference_file, csvfile)):
            print('MATCH:', f)
            os.remove(csvfile)
        else:
            print('MISSMATCH:', f)

if __name__== "__main__":
  main()
